### PR TITLE
Cleanup NPM package

### PR DESCRIPTION
**Pull request by jorrit**
Removes .jshintrc, .npmignore, test.js and .travis.yml from NPM package.

### CODE REVIEW

**Comment by w0rm** [comment]
@jorrit thanks for this pr! According to https://docs.npmjs.com/files/package.json#files the main file in package.json is included automatically, so it doesn't need to be specified in the "files" setting.

**Comment by jorrit** [comment]
Thanks, I did not know that! An empty array will suffice then. I have updated the commit.

**Comment by w0rm** [comment]
@jorrit thanks, merged. I guess it doesn't need to be published anytime soon. I'd rather wait for more changes.

**Comment by jorrit** [comment]
Of course, no hurry! Thanks for merging!

**Pull request merged**
