### PR TITLE
add `eslint`

### PR DESCRIPTION
**Pull request by gucong3000**
- add `eslint`
- converts `JSHint` file into `ESLint` file (use [polyjuice](https://www.npmjs.com/package/polyjuice))
- update `devDependencies`
- fix testcase error on windows

### CODE REVIEW

**Comment by w0rm** [comment]
@gucong3000 it broke tests for node 0.12

**Comment by TrySound** [comment]
@w0rm Let's remove it?

**Comment by w0rm** [comment]
@TrySound why? afaik postcss supports 0.12

**Comment by TrySound** [comment]
I guess it will be removed in near major.

**Comment by w0rm** [comment]
@TrySound then we have to wait for it and do a major bump

**Comment by w0rm** [comment]
@gucong3000 thank you! merged

**Pull request merged**
