### PR TITLE
Forgotten options parameter

### PR DESCRIPTION
**Pull request by Termina1**
So, I guess it should be like that?

### CODE REVIEW

**Comment by w0rm** [comment]
@Termina1 thanks! can you also add a test for this?

**Comment by Termina1** [comment]
@w0rm I added some tests for those options, also I believe the default behaviour should set showStack to ```true```. Or I don't understand the meaning of setting showStack to ```false``` in case of postcss syntax error.

**Comment by w0rm** [comment]
@Termina1 I think that in case of postcss syntax error the stack should be hidden, otherwise it has to be shown. The default [in gulp is to hide it](https://github.com/gulpjs/gulp-util/blob/master/lib/PluginError.js#L27).

**Comment by w0rm** [comment]
@Termina1 thanks I've just released 6.1.1

**Pull request merged**
