### PR TITLE
Update postcss-load-config v1.1.0...1.2.0

### PR DESCRIPTION
**Pull request by michael-ciniawsky**
@woorm Just minor to allow using file extensions for `.postcssrc` files e.g `(.postcssrc.js|json|yaml)`

### CODE REVIEW

**Comment by w0rm** [comment]
This is not needed, because https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

**Comment by michael-ciniawsky** [comment]
Alright, wouldn't hurt either :D, should I close  ?

**Comment by w0rm** [comment]
I merged, but there is no need to publish.

**Comment by michael-ciniawsky** [comment]
Yep, I understand didn't though about the SemVer `^` range. Thx 😛

**Pull request merged**
