### PR TITLE
New plugin options argument, and other fixes

### PR DESCRIPTION
**Pull request by ZeeCoder**
All the changes:
  * Removed deprecated usages of `new Buffer()`
  * Accepts a new third `pluginOptions` parameter with `handleResult`, which
    allows us to handle the results from PostCSS. (For example: handling messages
    from PostCSS plugins, which was not possible before.)
  * Declared the supported node version in package.json

### CODE REVIEW

**Comment by ZeeCoder** [comment]
Note that sourcemap test fails in master as well. 🤷‍♂️

**Comment by ZeeCoder** [comment]
Any chance this could get looked at?
cc @ai @w0rm

**Comment by ai** [comment]
I can move and release it (if I have a rights) if CI will be fixed

**Comment by ZeeCoder** [comment]
I might need help on that, as I said it's not my changes that break the CI, it's failing in the current master too.

**Comment by ai** [comment]
Sorry, you need to wait for @w0rm. I am very bad at Gul plugins.

**Comment by w0rm** [comment]
@ZeeCoder can you open an issue that explains your specific use case? An API that allows to pass a callback that can modify postcss result seems a bit hacky to me: 
1. I'd rather not have any configuration that is not a part of https://www.npmjs.com/package/postcss-load-config
2. what you try to address seems to be a shortcoming of gulp, where the only output is a vinyl file. A stream of files that uses side effects to extract additional stuff feels a bit wrong.

As for `buffer.from`, could you please open a separate PR for it? 

Let's not modify the changelog, it should be done only when a new version is published.

**Comment by ZeeCoder** [comment]
Closed in favour of #151 and #152

**Pull request closed without merging**
